[theme]
primaryColor = "#00FF7F"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#161b22"
textColor = "#FAFAFA"
font = "sans serif"

[client]
toolbarMode = "minimal" # Hides the top right "hamburger" menu to look like a real app
