[theme]
primaryColor = "#00FF00"  # Public's Neon Green
backgroundColor = "#000000" # Pure Black background
secondaryBackgroundColor = "#121212" # Dark Grey for sidebar/cards
textColor = "#FFFFFF"
font = "sans serif"

[client]
toolbarMode = "minimal"
